when:
  - event: push
  - event: pull_request
    branch: master

steps:
  - name: setup attic cache
    image: nixos/nix
    secrets: [ ATTIC_TOKEN ]
    commands:
      - nix --extra-expiramental-features "nix-command flakes" shell nixpkgs#attic-client
      - attic login hydrogen http://attic.hydrogen.lan/ $ATTIC_TOKEN
      - attic use local
