name: checks

on:
  push:

jobs:
  eval-matrix:
    runs-on: native
    steps:
    - name: Checkout repository
      uses: http://git.hydrogen.lan/actions/checkout@v4

    - name: nix version
      run: |
        nix --version

    - name: nix flake show
      run: |
        nix flake show

    - name: nix flake check
      run: |
        nix flake check
