matrix:
  NIXOS_HOST:
    - avalon
    - hydrogen
    - odyssey
    - quantum

steps:
  - name: nixos build ${NIXOS_HOST}
    when:
      - event: push
      - event: manual
      - event: pull_request
        branch: master
    image: nixos/nix
    secrets: [ ATTIC_TOKEN ]
    volumes:
      - /data/nix:/mnt/nix
    commands: |
      echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      nix shell nixpkgs#attic-client
      attic login hydrogen http://attic.hydrogen.lan/ $ATTIC_TOKEN
      attic use local
      nix build -j 16 --cores 24 --store unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt .#nixosConfigurations.${NIXOS_HOST}.config.system.build.toplevel
      attic push local $(realpath result)
