matrix:
  include:
    - ARCH: x86_64-linux
      NIXOS_USER: jeff
      NIXOS_HOST: avalon

    - ARCH: x86_64-linux
      NIXOS_USER: jeff
      NIXOS_HOST: hydrogen

    - ARCH: x86_64-linux
      NIXOS_USER: jeff
      NIXOS_HOST: odyssey

    - ARCH: x86_64-linux
      NIXOS_USER: jeff
      NIXOS_HOST: quantum

    - ARCH: x86_64-linux
      NIXOS_USER: dad
      NIXOS_HOST: dad

# TODO: move experimental-features to custom docker container
steps:
  - name: nixos build ${NIXOS_HOST}
    when:
      - event: push
      - event: manual
      - event: pull_request
        branch: master
        repo:
          exclude:
            - "QuantumCoded/nixos"
    image: nixos/nix
    volumes:
      - /nix:/host/nix:ro
    commands: |
      echo 'experimental-features = nix-command flakes' > /etc/nix/nix.conf
      NIX_REMOTE=daemon nix build -j 8 --cores 12 --store unix:///host/nix/var/nix/daemon-socket/socket?root=/host .#nixosConfigurations.${NIXOS_HOST}.config.system.build.toplevel

  - name: home-manager ${NIXOS_USER}@${NIXOS_HOST} build check
    when:
      - event: push
      - event: manual
      - event: pull_request
        branch: master
        repo:
          exclude:
            - "QuantumCoded/nixos"
    image: nixos/nix
    commands: |
      echo 'experimental-features = nix-command flakes' > /etc/nix/nix.conf
      nix build .#homeConfiguration.${ARCH}.${NIXOS_HOST}.${NIXOS_USER}.activationPackage --dry-run
