matrix:
  NIXOS_HOST:
    - avalon
    - hydrogen
    - odyssey
    - quantum

steps:
  - name: nixos build ${NIXOS_HOST}
    when:
      - event: push
      - event: manual
      - event: pull_request
        branch: master
    image: nixos/nix
    secrets: [ ATTIC_TOKEN ]
    volumes:
      - /nix:/host/nix:ro
    commands: |
      echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      NIX_REMOTE=daemon nix build -j 8 --cores 12 --store unix:///host/nix/var/nix/daemon-socket/socket?root=/host .#nixosConfigurations.${NIXOS_HOST}.config.system.build.toplevel
