# TODO: move experimental-features to custom docker container
steps:
    # TODO: nixpkgs-fmt should be on the custom container
  - name: nixpkgs-fmt check
    when:
      - event: push
      - event: manual
      - event: pull_request
        branch: master
        repo:
          exclude:
            - "QuantumCoded/nixos"
    image: nixos/nix
    commands: |
      echo 'experimental-features = nix-command flakes' > /etc/nix/nix.conf
      nix run nixpkgs#nixpkgs-fmt -- --check .

  - name: nix flake check
    when:
      - event: push
      - event: manual
      - event: pull_request
        branch: master
        repo:
          exclude:
            - "QuantumCoded/nixos"
    image: nixos/nix
    commands: |
      echo 'experimental-features = nix-command flakes' > /etc/nix/nix.conf
      NIX_REMOTE=daemon nix flake check --store unix:///host/nix/var/nix/daemon-socket/socket?root=/host
