name: "Nix Build Check"
on:
  push:
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]
jobs:
  quantum:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: nix build .#nixosConfigurations.quantum.config.system.build.toplevel --dry-run
  
  odyssey:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: nix build .#nixosConfigurations.odyssey.config.system.build.toplevel --dry-run
