name: "HomeManager Build Check for Jeff on Hydrogen"
on:
  push:
    branches: [ "*" ]
  pull_request: 
    branches: [ "*" ]
jobs:
  home-manager-jeff-hydrogen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: nix build .#homeConfigurations.jeff@odyssey.activationPackage --dry-run