name: "Nix Format Check"
on:
  push:
    branches: [ "*" ]
  pull_request: 
    branches: [ "*" ]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: workflow/nix-shell-action@v3.3.0
      with:
        packages: nixpkgs-fmt
        script: nixpkgs-fmt --check .
